version: '2'
services:
  hl-sohoxi:
    image: hookandloop/hl-builder:1.0.0
    container_name: hl_sohoxi
    tty: true
    ports:
      - 4000:4000
      - 35729:35729
    volumes: 
      - ".:/controls"
    working_dir: /controls
    command: ./bin/docker-entrypoint.sh
